
package pl.agh.edu.is.webdb.privateservices;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CrudService", targetNamespace = "http://privateservices.webDB.is.edu.agh.pl/", wsdlLocation = "http://ntesting-aolkuski.rhcloud.com/webDBwar/CrudService?wsdl")
public class CrudService
    extends Service
{

    private final static URL CRUDSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(pl.agh.edu.is.webdb.privateservices.CrudService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = pl.agh.edu.is.webdb.privateservices.CrudService.class.getResource(".");
            url = new URL(baseUrl, "http://ntesting-aolkuski.rhcloud.com/webDBwar/CrudService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://ntesting-aolkuski.rhcloud.com/webDBwar/CrudService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CRUDSERVICE_WSDL_LOCATION = url;
    }

    public CrudService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CrudService() {
        super(CRUDSERVICE_WSDL_LOCATION, new QName("http://privateservices.webDB.is.edu.agh.pl/", "CrudService"));
    }

    /**
     * 
     * @return
     *     returns CrudServiceInterface
     */
    @WebEndpoint(name = "CrudServicePort")
    public CrudServiceInterface getCrudServicePort() {
        return super.getPort(new QName("http://privateservices.webDB.is.edu.agh.pl/", "CrudServicePort"), CrudServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CrudServiceInterface
     */
    @WebEndpoint(name = "CrudServicePort")
    public CrudServiceInterface getCrudServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://privateservices.webDB.is.edu.agh.pl/", "CrudServicePort"), CrudServiceInterface.class, features);
    }

}
