
package pl.agh.edu.is.webdb.privateservices;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CrudServiceInterface", targetNamespace = "http://privateservices.webDB.is.edu.agh.pl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CrudServiceInterface {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addDiscount", targetNamespace = "http://privateservices.webDB.is.edu.agh.pl/", className = "pl.agh.edu.is.webdb.privateservices.AddDiscount")
    @ResponseWrapper(localName = "addDiscountResponse", targetNamespace = "http://privateservices.webDB.is.edu.agh.pl/", className = "pl.agh.edu.is.webdb.privateservices.AddDiscountResponse")
    public void addDiscount(
        @WebParam(name = "arg0", targetNamespace = "")
        Discount arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "modifyGroup", targetNamespace = "http://privateservices.webDB.is.edu.agh.pl/", className = "pl.agh.edu.is.webdb.privateservices.ModifyGroup")
    @ResponseWrapper(localName = "modifyGroupResponse", targetNamespace = "http://privateservices.webDB.is.edu.agh.pl/", className = "pl.agh.edu.is.webdb.privateservices.ModifyGroupResponse")
    public void modifyGroup(
        @WebParam(name = "arg0", targetNamespace = "")
        Group arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addApplicationForm", targetNamespace = "http://privateservices.webDB.is.edu.agh.pl/", className = "pl.agh.edu.is.webdb.privateservices.AddApplicationForm")
    @ResponseWrapper(localName = "addApplicationFormResponse", targetNamespace = "http://privateservices.webDB.is.edu.agh.pl/", className = "pl.agh.edu.is.webdb.privateservices.AddApplicationFormResponse")
    public void addApplicationForm(
        @WebParam(name = "arg0", targetNamespace = "")
        Application arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteRight", targetNamespace = "http://privateservices.webDB.is.edu.agh.pl/", className = "pl.agh.edu.is.webdb.privateservices.DeleteRight")
    @ResponseWrapper(localName = "deleteRightResponse", targetNamespace = "http://privateservices.webDB.is.edu.agh.pl/", className = "pl.agh.edu.is.webdb.privateservices.DeleteRightResponse")
    public void deleteRight(
        @WebParam(name = "arg0", targetNamespace = "")
        Right arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteGroup", targetNamespace = "http://privateservices.webDB.is.edu.agh.pl/", className = "pl.agh.edu.is.webdb.privateservices.DeleteGroup")
    @ResponseWrapper(localName = "deleteGroupResponse", targetNamespace = "http://privateservices.webDB.is.edu.agh.pl/", className = "pl.agh.edu.is.webdb.privateservices.DeleteGroupResponse")
    public void deleteGroup(
        @WebParam(name = "arg0", targetNamespace = "")
        Group arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteSeller", targetNamespace = "http://privateservices.webDB.is.edu.agh.pl/", className = "pl.agh.edu.is.webdb.privateservices.DeleteSeller")
    @ResponseWrapper(localName = "deleteSellerResponse", targetNamespace = "http://privateservices.webDB.is.edu.agh.pl/", className = "pl.agh.edu.is.webdb.privateservices.DeleteSellerResponse")
    public void deleteSeller(
        @WebParam(name = "arg0", targetNamespace = "")
        Seller arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addSeller", targetNamespace = "http://privateservices.webDB.is.edu.agh.pl/", className = "pl.agh.edu.is.webdb.privateservices.AddSeller")
    @ResponseWrapper(localName = "addSellerResponse", targetNamespace = "http://privateservices.webDB.is.edu.agh.pl/", className = "pl.agh.edu.is.webdb.privateservices.AddSellerResponse")
    public void addSeller(
        @WebParam(name = "arg0", targetNamespace = "")
        Seller arg0);

    /**
     * 
     * @return
     *     returns java.util.List<pl.agh.edu.is.webdb.privateservices.Application>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllApplications", targetNamespace = "http://privateservices.webDB.is.edu.agh.pl/", className = "pl.agh.edu.is.webdb.privateservices.GetAllApplications")
    @ResponseWrapper(localName = "getAllApplicationsResponse", targetNamespace = "http://privateservices.webDB.is.edu.agh.pl/", className = "pl.agh.edu.is.webdb.privateservices.GetAllApplicationsResponse")
    public List<Application> getAllApplications();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteDiscount", targetNamespace = "http://privateservices.webDB.is.edu.agh.pl/", className = "pl.agh.edu.is.webdb.privateservices.DeleteDiscount")
    @ResponseWrapper(localName = "deleteDiscountResponse", targetNamespace = "http://privateservices.webDB.is.edu.agh.pl/", className = "pl.agh.edu.is.webdb.privateservices.DeleteDiscountResponse")
    public void deleteDiscount(
        @WebParam(name = "arg0", targetNamespace = "")
        Discount arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addRight", targetNamespace = "http://privateservices.webDB.is.edu.agh.pl/", className = "pl.agh.edu.is.webdb.privateservices.AddRight")
    @ResponseWrapper(localName = "addRightResponse", targetNamespace = "http://privateservices.webDB.is.edu.agh.pl/", className = "pl.agh.edu.is.webdb.privateservices.AddRightResponse")
    public void addRight(
        @WebParam(name = "arg0", targetNamespace = "")
        Right arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "modifySeller", targetNamespace = "http://privateservices.webDB.is.edu.agh.pl/", className = "pl.agh.edu.is.webdb.privateservices.ModifySeller")
    @ResponseWrapper(localName = "modifySellerResponse", targetNamespace = "http://privateservices.webDB.is.edu.agh.pl/", className = "pl.agh.edu.is.webdb.privateservices.ModifySellerResponse")
    public void modifySeller(
        @WebParam(name = "arg0", targetNamespace = "")
        Seller arg0);

    /**
     * 
     * @return
     *     returns java.util.List<pl.agh.edu.is.webdb.privateservices.Discount>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllDiscounts", targetNamespace = "http://privateservices.webDB.is.edu.agh.pl/", className = "pl.agh.edu.is.webdb.privateservices.GetAllDiscounts")
    @ResponseWrapper(localName = "getAllDiscountsResponse", targetNamespace = "http://privateservices.webDB.is.edu.agh.pl/", className = "pl.agh.edu.is.webdb.privateservices.GetAllDiscountsResponse")
    public List<Discount> getAllDiscounts();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "modifyRight", targetNamespace = "http://privateservices.webDB.is.edu.agh.pl/", className = "pl.agh.edu.is.webdb.privateservices.ModifyRight")
    @ResponseWrapper(localName = "modifyRightResponse", targetNamespace = "http://privateservices.webDB.is.edu.agh.pl/", className = "pl.agh.edu.is.webdb.privateservices.ModifyRightResponse")
    public void modifyRight(
        @WebParam(name = "arg0", targetNamespace = "")
        Right arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteApplicationForm", targetNamespace = "http://privateservices.webDB.is.edu.agh.pl/", className = "pl.agh.edu.is.webdb.privateservices.DeleteApplicationForm")
    @ResponseWrapper(localName = "deleteApplicationFormResponse", targetNamespace = "http://privateservices.webDB.is.edu.agh.pl/", className = "pl.agh.edu.is.webdb.privateservices.DeleteApplicationFormResponse")
    public void deleteApplicationForm(
        @WebParam(name = "arg0", targetNamespace = "")
        Application arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "modifyDiscount", targetNamespace = "http://privateservices.webDB.is.edu.agh.pl/", className = "pl.agh.edu.is.webdb.privateservices.ModifyDiscount")
    @ResponseWrapper(localName = "modifyDiscountResponse", targetNamespace = "http://privateservices.webDB.is.edu.agh.pl/", className = "pl.agh.edu.is.webdb.privateservices.ModifyDiscountResponse")
    public void modifyDiscount(
        @WebParam(name = "arg0", targetNamespace = "")
        Discount arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "modifyFormField", targetNamespace = "http://privateservices.webDB.is.edu.agh.pl/", className = "pl.agh.edu.is.webdb.privateservices.ModifyFormField")
    @ResponseWrapper(localName = "modifyFormFieldResponse", targetNamespace = "http://privateservices.webDB.is.edu.agh.pl/", className = "pl.agh.edu.is.webdb.privateservices.ModifyFormFieldResponse")
    public void modifyFormField(
        @WebParam(name = "arg0", targetNamespace = "")
        FormField arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addFormField", targetNamespace = "http://privateservices.webDB.is.edu.agh.pl/", className = "pl.agh.edu.is.webdb.privateservices.AddFormField")
    @ResponseWrapper(localName = "addFormFieldResponse", targetNamespace = "http://privateservices.webDB.is.edu.agh.pl/", className = "pl.agh.edu.is.webdb.privateservices.AddFormFieldResponse")
    public void addFormField(
        @WebParam(name = "arg0", targetNamespace = "")
        FormField arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addGroup", targetNamespace = "http://privateservices.webDB.is.edu.agh.pl/", className = "pl.agh.edu.is.webdb.privateservices.AddGroup")
    @ResponseWrapper(localName = "addGroupResponse", targetNamespace = "http://privateservices.webDB.is.edu.agh.pl/", className = "pl.agh.edu.is.webdb.privateservices.AddGroupResponse")
    public void addGroup(
        @WebParam(name = "arg0", targetNamespace = "")
        Group arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isGroupAllowed", targetNamespace = "http://privateservices.webDB.is.edu.agh.pl/", className = "pl.agh.edu.is.webdb.privateservices.IsGroupAllowed")
    @ResponseWrapper(localName = "isGroupAllowedResponse", targetNamespace = "http://privateservices.webDB.is.edu.agh.pl/", className = "pl.agh.edu.is.webdb.privateservices.IsGroupAllowedResponse")
    public Boolean isGroupAllowed(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @return
     *     returns java.util.List<pl.agh.edu.is.webdb.privateservices.Seller>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllSellers", targetNamespace = "http://privateservices.webDB.is.edu.agh.pl/", className = "pl.agh.edu.is.webdb.privateservices.GetAllSellers")
    @ResponseWrapper(localName = "getAllSellersResponse", targetNamespace = "http://privateservices.webDB.is.edu.agh.pl/", className = "pl.agh.edu.is.webdb.privateservices.GetAllSellersResponse")
    public List<Seller> getAllSellers();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "modifyApplicationForm", targetNamespace = "http://privateservices.webDB.is.edu.agh.pl/", className = "pl.agh.edu.is.webdb.privateservices.ModifyApplicationForm")
    @ResponseWrapper(localName = "modifyApplicationFormResponse", targetNamespace = "http://privateservices.webDB.is.edu.agh.pl/", className = "pl.agh.edu.is.webdb.privateservices.ModifyApplicationFormResponse")
    public void modifyApplicationForm(
        @WebParam(name = "arg0", targetNamespace = "")
        Application arg0);

    /**
     * 
     * @return
     *     returns java.util.List<pl.agh.edu.is.webdb.privateservices.Right>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllRights", targetNamespace = "http://privateservices.webDB.is.edu.agh.pl/", className = "pl.agh.edu.is.webdb.privateservices.GetAllRights")
    @ResponseWrapper(localName = "getAllRightsResponse", targetNamespace = "http://privateservices.webDB.is.edu.agh.pl/", className = "pl.agh.edu.is.webdb.privateservices.GetAllRightsResponse")
    public List<Right> getAllRights();

    /**
     * 
     * @return
     *     returns java.util.List<pl.agh.edu.is.webdb.privateservices.FormField>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllFormFields", targetNamespace = "http://privateservices.webDB.is.edu.agh.pl/", className = "pl.agh.edu.is.webdb.privateservices.GetAllFormFields")
    @ResponseWrapper(localName = "getAllFormFieldsResponse", targetNamespace = "http://privateservices.webDB.is.edu.agh.pl/", className = "pl.agh.edu.is.webdb.privateservices.GetAllFormFieldsResponse")
    public List<FormField> getAllFormFields();

    /**
     * 
     * @return
     *     returns java.util.List<pl.agh.edu.is.webdb.privateservices.Group>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllGroups", targetNamespace = "http://privateservices.webDB.is.edu.agh.pl/", className = "pl.agh.edu.is.webdb.privateservices.GetAllGroups")
    @ResponseWrapper(localName = "getAllGroupsResponse", targetNamespace = "http://privateservices.webDB.is.edu.agh.pl/", className = "pl.agh.edu.is.webdb.privateservices.GetAllGroupsResponse")
    public List<Group> getAllGroups();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteFormField", targetNamespace = "http://privateservices.webDB.is.edu.agh.pl/", className = "pl.agh.edu.is.webdb.privateservices.DeleteFormField")
    @ResponseWrapper(localName = "deleteFormFieldResponse", targetNamespace = "http://privateservices.webDB.is.edu.agh.pl/", className = "pl.agh.edu.is.webdb.privateservices.DeleteFormFieldResponse")
    public void deleteFormField(
        @WebParam(name = "arg0", targetNamespace = "")
        FormField arg0);

}
